name: circly
description: Défi du mois
author: "Ionys"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  just_debounce_it: ^3.0.0+2
  mapbox_search: ^2.0.0
  google_maps: ^3.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
